### ISSUE TITLE
ImportError: /lib/aarch64-linux-gnu/libgstreamer-1.0.so.0: file too short

### ISSUE THREAD

**Issue by immnas** [NVIDIA-AI-IOT/jetnet#13]
I am using jetson xavier nx with jetpack 5.0.2.
I am running the docker setup as suggested.
i got first error
docker: Error response from daemon: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'csv'
invoking the NVIDIA Container Runtime Hook directly (e.g. specifying the docker --gpus flag) is not supported. Please use the NVIDIA Container Runtime instead.: unknown.

when i removed the --gpus flag
its worked and i entered at docker command prompt.
when i run the following command
jetnet demo jetnet.easyocr.EASYOCR_EN_TRT_FP26

Traceback (most recent call last):
  File "/usr/local/bin/jetnet", line 11, in <module>
    load_entry_point('jetnet', 'console_scripts', 'jetnet')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/jetnet/jetnet/__main__.py", line 26, in <module>
    from jetnet.demo.demo import (
  File "/jetnet/jetnet/demo/demo.py", line 20, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 96, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 86, in bootstrap
    import cv2
ImportError: /lib/aarch64-linux-gnu/libgstreamer-1.0.so.0: file too short

**Comment by jaybdub** [comment]
Hi @immnas ,

Thanks for reaching out!

It's odd that the ``--gpus`` flag isn't working.  I'm curious why this is the case, perhaps it's the root of the problem.

Have you configured docker to use the nvidia runtime?  You can do that by editing the /et/docker/daemon.json file, like this:

https://github.com/dusty-nv/jetson-containers#docker-default-runtime

Please let me know if this helps or not.

Best,
John

**Comment by immnas** [comment]
Hi

I am able to run dusty-nv with docker and without docker properly.
